### PR TITLE
Move to go 1.23 and fix CI

### PR DESCRIPTION
**Pull request by galt-tr**

### CODE REVIEW

**Comment by mrz1836** [comment]
@galt-tr linter needs to be bumped in `go.mk` to `1.61.0`

**Comment by galt-tr** [comment]
@mrz1836 :pray:

**Comment by mrz1836** [comment]
Now the `G115` needs to be suppressed in the golangci lint

And the other testify lint errors just need to be fixed

**Comment by galt-tr** [comment]
Am I crazy to just not run testifylint? Some of the changes felt unecessary.

I can just open an issue to track reenabling it if so

**Comment by mrz1836** [comment]
@galt-tr its just enforcing best practices for the `testify` package 🤷

**Review by mrz1836 — APPROVED** [review]
LGTM

**Comment by galt-tr** [comment]
https://github.com/bitcoin-sv/alert-system/issues/148

to track

**Pull request merged**
